param appServicePlanResourceName string
param appServiceLocation string
param loreAgentWebAppName string
param mageApiWebAppName string

resource asp 'Microsoft.Web/serverfarms@2024-11-01' = {
  name: appServicePlanResourceName
  location: appServiceLocation
  kind: 'linux'
  properties: {
    reserved: true
  }
  sku: {
    tier: 'PremiumV3'
    name: 'P1V3'
  }
}

resource webAgent 'Microsoft.Web/sites@2024-11-01' = {
  name: loreAgentWebAppName
  location: appServiceLocation
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    siteConfig: {
      appSettings: []
      linuxFxVersion: 'sitecontainers'
      acrUseManagedIdentityCreds: true
      alwaysOn: true
    }
    serverFarmId: asp.id
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource webMageAPI 'Microsoft.Web/sites@2024-11-01' = {
  name: mageApiWebAppName
  location: appServiceLocation
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    siteConfig: {
      appSettings: []
      linuxFxVersion: 'sitecontainers'
      acrUseManagedIdentityCreds: true
      alwaysOn: true
    }
    serverFarmId: asp.id
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource appSettings 'Microsoft.Web/sites/config@2024-11-01' = {
  name: 'appsettings'
  parent: webMageAPI
  properties: {
    SERVER_URL: 'https://${webMageAPI.properties.defaultHostName}'
  }
}

output loreAgentResourceName string = webAgent.name
output webMageApiResourceName string = webMageAPI.name
output webApiMageEndpoint string = 'https://${webMageAPI.properties.defaultHostName}'
output principalIds array = [
  webAgent.identity.principalId
  webMageAPI.identity.principalId
]
