param appServicePlanResourceName string
param appServiceLocation string
param loreAgentWebAppName string

resource asp 'Microsoft.Web/serverfarms@2024-11-01' = {
  name: appServicePlanResourceName
  location: appServiceLocation
  kind: 'linux'
  properties: {
    reserved: true
  }
  sku: {
    tier: 'PremiumV3'
    name: 'P1V3'
  }
}

resource web 'Microsoft.Web/sites@2024-11-01' = {
  name: loreAgentWebAppName
  location: appServiceLocation
  kind: 'app,linux,container'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    siteConfig: {
      appSettings: []
      linuxFxVersion: 'sitecontainers'
      acrUseManagedIdentityCreds: true
      alwaysOn: true
    }
    serverFarmId: asp.id
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

output loreAgentResourceName string = web.name
